### ISSUE TITLE
add unit tests and CI

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-utilities#7]
scan code is used to verify proper licenses, and common code formats across a number of repositories.

this repo should have unit tests that validate that scan code is working as expected; with Travis CI configured to run them.

**Comment by rabbah** [comment]
@mrutkows I see tests per https://github.com/apache/incubator-openwhisk-utilities/blob/master/scancode/test.sh is this ok to close?

**Comment by dgrove-oss** [comment]
done long time ago...
